#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
if (file_exists(__DIR__ . '/autoload.local.php')) {
  require_once __DIR__ . '/autoload.local.php';
}

//error_reporting(E_ERROR & E_PARSE);
error_reporting(E_ALL);

\CiUtil\Command\LsCommand::main($argv);