#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
if (file_exists(__DIR__ . '/autoload.local.php')) {
  require_once __DIR__ . '/autoload.local.php';
}
\CiUtil\Command\AntagonistCommand::main($argv);
